POST http://localhost:8081/farmers
Content-Type: application/json

{
  "name": "Ravi Kumar",
  "phone": "9876543210",
  "location": "Tamil Nadu",
  "landArea": 5.5,
  "soilType": "Loamy"
}

###
GET http://localhost:8081/farmers
###

DELETE http://localhost:8081/farmers/2
###
PUT http://localhost:8081/farmers/1
Content-Type: application/json

{
  "name": "Updated Farmer",
  "phone": "9999999999",
  "location": "Kerala",
  "landArea": 10,
  "soilType": "Clay"
}
###
POST http://localhost:8081/farmers
Content-Type: application/json

{
  "name": "",
  "phone": "123",
  "location": "",
  "landArea": -5,
  "soilType": ""
}
###
GET http://localhost:8081/farmers/paginated?page=0&size=2&sort=name,asc

###
DELETE http://localhost:8081/farmers/999

###
POST http://localhost:8081/farmers/1/crops
Content-Type: application/json

{
  "cropName": "Wheat",
  "cropCategory": "Cereal",
  "season": "Rabi",
  "sowingDate": "2024-11-01",
  "harvestDate": "2025-03-15",
  "expectedYield": 500,
  "actualYield": 450,
  "pricePerKg": 25
}
###
GET http://localhost:8081/farmers/1/crops/revenue