spring.application.name=smart-agriculture
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/smart_agriculture?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081